"""add year

Revision ID: f40edbc57986
Revises: 02348219e792
Create Date: 2023-12-27 22:21:47.894626

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "f40edbc57986"
down_revision = "02348219e792"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("song", sa.Column("year", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_song_year"), "song", ["year"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_song_year"), table_name="song")
    op.drop_column("song", "year")
    # ### end Alembic commands ###
